apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-agent-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-agent-app
  template:
    metadata:
      labels:
        app: stock-agent-app
    spec:
      containers:
        - name: app
          image: stock-agent-ai:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: stock-agent-config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
